name: Deploy From Cache

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout OrnaCodexCrawler
        uses: actions/checkout@v4
        with:
          repository: '67au/OrnaCodexCrawler'
          path: './crawler'
      - name: Download Codex from Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: codex-data
          path: './crawler/tmp'
          github_token: ${{ secrets.GH_PAT }}
          workflow: upload-data.yml
          repo: 67au/OrnaCodexCrawler
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install scrapy
      - name: Extract Codex
        run: |
          cd crawler
          python script.py codex -g -o ../src/assets/json/codex.json
          cd ..
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          echo 'ORNA_URL=${{ vars.TARGET }}' >> .env
          echo "DATA_CREATED=$(cat ./crawler/tmp/finished)" >> .env
          yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
